// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM39aX_Q_jM5Qnhsjr2gdPkNk_g9I4xZ8',
    appId: '1:295411715838:android:08eab15b19f430b2c79faf',
    messagingSenderId: '295411715838',
    projectId: 'service-reservation-system',
    storageBucket: 'service-reservation-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCebnyu-ZQC5fOdabBZAdDuAtXIVamT6gM',
    appId: '1:295411715838:ios:1be25c8cb1c0f9c2c79faf',
    messagingSenderId: '295411715838',
    projectId: 'service-reservation-system',
    storageBucket: 'service-reservation-system.firebasestorage.app',
    iosBundleId: 'com.example.serviceReservationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QzjWOPQ4CTqu7TA-FAU_u9jQC9HzcPc',
    appId: '1:295411715838:web:b9cf7ea61fc74daac79faf',
    messagingSenderId: '295411715838',
    projectId: 'service-reservation-system',
    authDomain: 'service-reservation-system.firebaseapp.com',
    storageBucket: 'service-reservation-system.firebasestorage.app',
    measurementId: 'G-J7PCKF42KV',
  );
}
